### ISSUE TITLE
Support for editable key-value pairs

### ISSUE THREAD

**Issue by jsbrittain** [kraemer-lab/GRAPEVNE#278]
The GRAPEVNE editor allows values and lists to be edited, but does not provide edit facilities for key-value pairs.

We propose to resolve this by specifying a 'list of' key-values in the parameters structure, e.g.
```yaml
header:
  - k1: v1
  - k2: v2
```
would be an editable list, but
```yaml
header:
  k1: v1
  k2: v2
```
would be separate editable fields. At present, lists of strings are editable as an 'expandable' list. This concept could be extended to support arbitrary (potentially nested) list items.

Related to: https://github.com/kraemer-lab/vneyard/issues/20
